traitement_polar_node:
  ros__parameters:
    polar_enable_gaussian: false
    polar_gaussian_sigma: 1.0
    polar_enable_median: false
    polar_median_kernel: 3
    polar_enable_loss: false
    polar_loss_window_size: 5
    polar_enable_frost: true
    polar_frost_window_size: 5
    polar_frost_damping: 3.1
    polar_enable_log_compression: false
    polar_log_scale: 30.0
