sonar_mock:
  ros__parameters:
    noise_level: 2.5
    enable_median: true
    median_kernel: 5
    enable_gaussian: true
    gaussian_sigma: 3.5
    enable_contrast: true
    contrast_clip: 0.3
    enable_range_comp: false
    range_comp_alpha: 0.01
